# Generated by Django 6.0.6 on 2026-06-07 19:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('meal_type', models.CharField(choices=[('breakfast', 'إفطار'), ('lunch', 'غداء'), ('dinner', 'عشاء'), ('snack', 'سناك')], max_length=20, verbose_name='نوع الوجبة')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة الطعام',
                'verbose_name_plural': 'فئات الطعام',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('cashier', 'كاشير')], default='cashier', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الطبق')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعرات')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='items', to='core.foodcategory', verbose_name='الفئات')),
            ],
            options={
                'verbose_name': 'طبق',
                'verbose_name_plural': 'الأطباق',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('lose', 'إنقاص الوزن'), ('gain', 'زيادة الوزن')], max_length=10, verbose_name='الهدف')),
                ('meals_per_day', models.IntegerField(verbose_name='عدد الوجبات يومياً')),
                ('days', models.IntegerField(choices=[(7, '7 أيام'), (14, '14 يوم'), (21, '21 يوم'), (28, '28 يوم')], verbose_name='عدد الأيام')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (ريال)')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'unique_together': {('goal', 'meals_per_day', 'days')},
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('meal_types', models.CharField(max_length=100, verbose_name='أنواع الوجبات المشمولة')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscriptionplan', verbose_name='خطة الاشتراك')),
            ],
            options={
                'verbose_name': 'مشترك',
                'verbose_name_plural': 'المشتركون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='رقم اليوم')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'إرسال يومي',
                'verbose_name_plural': 'الإرسالات اليومية',
                'unique_together': {('subscriber', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='DailyMealSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='رقم اليوم')),
                ('meal_type', models.CharField(choices=[('breakfast', 'إفطار'), ('lunch', 'غداء'), ('dinner', 'عشاء'), ('snack', 'سناك')], max_length=20, verbose_name='نوع الوجبة')),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fooditem', verbose_name='الطبق المختار')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'اختيار وجبة',
                'verbose_name_plural': 'اختيارات الوجبات',
                'unique_together': {('subscriber', 'day_number', 'meal_type')},
            },
        ),
    ]
