# Generated by Django 6.0.6 on 2026-06-07 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={},
        ),
        migrations.AlterField(
            model_name='dailymealselection',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20, verbose_name='نوع الوجبة'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='days',
            field=models.IntegerField(choices=[(7, '7 Days'), (14, '14 Days'), (21, '21 Days'), (28, '28 Days')]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='goal',
            field=models.CharField(choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='meals_per_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.subscriber')),
            ],
            options={
                'unique_together': {('subscriber', 'day_number')},
            },
        ),
    ]
