# Generated by Django 6.0.6 on 2026-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='custom_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='أيام مخصصة'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='سعر مخصص'),
        ),
    ]
